services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: davide
      MONGO_INITDB_ROOT_PASSWORD: davide
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: davide
      ME_CONFIG_MONGODB_ADMINPASSWORD: davide
      ME_CONFIG_MONGODB_URL: mongodb://davide:davide@mongo:27017/
      ME_CONFIG_BASICAUTH: false


volumes:
  mongo_data: {}
  